export const changeCKEditorCssVars = (theme) => {
  document.documentElement.style.setProperty(
    '--ck-custom-background',
    theme.palette.background.paper,
  );
  document.documentElement.style.setProperty(
    '--ck-custom-foreground',
    theme.palette.text.primary,
  );
  document.documentElement.style.setProperty(
    '--ck-custom-border',
    theme.palette.divider,
  );
  document.documentElement.style.setProperty(
    '--ck-custom-white',
    theme.palette.common.white,
  );
  document.documentElement.style.setProperty(
    '--ck-color-base-background',
    theme.palette.background.paper,
  );
  document.documentElement.style.setProperty(
    '--ck-color-base-foreground',
    theme.palette.text.primary,
  );
  document.documentElement.style.setProperty(
    '--ck-color-focus-border',
    theme.palette.primary.main,
  );
  document.documentElement.style.setProperty(
    '--ck-color-text',
    theme.palette.text.primary,
  );
  document.documentElement.style.setProperty(
    '--ck-color-shadow-drop',
    theme.palette.action.hover,
  );
  document.documentElement.style.setProperty(
    '--ck-color-shadow-inner',
    theme.palette.action.selected,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-default-background',
    theme.palette.action,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-default-hover-background',
    theme.palette.action.hover,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-default-active-background',
    theme.palette.action.selected,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-default-active-shadow',
    theme.palette.action.selected,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-default-disabled-background',
    theme.palette.action.disabledBackground,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-on-background',
    theme.palette.action.hover,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-on-hover-background',
    theme.palette.action.hover,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-on-active-background',
    theme.palette.action.selected,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-on-active-shadow',
    theme.palette.action.selected,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-on-disabled-background',
    theme.palette.action.disabledBackground,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-action-background',
    theme.palette.primary.background,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-action-hover-background',
    theme.palette.primary.background,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-action-active-background',
    theme.palette.primary.background,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-action-active-shadow',
    theme.palette.primary.background,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-action-disabled-background',
    theme.palette.action.disabledBackground,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-action-text',
    theme.palette.common.white,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-save',
    theme.palette.success.main,
  );
  document.documentElement.style.setProperty(
    '--ck-color-button-cancel',
    theme.palette.error.main,
  );
  document.documentElement.style.setProperty(
    '--ck-color-dropdown-panel-background',
    theme.palette.background.paper,
  );
  document.documentElement.style.setProperty(
    '--ck-color-dropdown-panel-border',
    theme.palette.divider,
  );
  document.documentElement.style.setProperty(
    '--ck-color-split-button-hover-background',
    theme.palette.action.hover,
  );
  document.documentElement.style.setProperty(
    '--ck-color-split-button-hover-border',
    theme.palette.action.hover,
  );
  document.documentElement.style.setProperty(
    '--ck-color-input-background',
    theme.palette.background.paper,
  );
  document.documentElement.style.setProperty(
    '--ck-color-input-border',
    theme.palette.divider,
  );
  document.documentElement.style.setProperty(
    '--ck-color-input-text',
    theme.palette.text.primary,
  );
  document.documentElement.style.setProperty(
    '--ck-color-input-disabled-background',
    theme.palette.action.disabledBackground,
  );
  document.documentElement.style.setProperty(
    '--ck-color-input-disabled-border',
    theme.palette.action.disabledBackground,
  );
  document.documentElement.style.setProperty(
    '--ck-color-input-disabled-text',
    theme.palette.text.disabled,
  );
  document.documentElement.style.setProperty(
    '--ck-color-labeled-field-label-background',
    theme.palette.background.paper,
  );
  document.documentElement.style.setProperty(
    '--ck-color-list-background',
    theme.palette.background.paper,
  );
  document.documentElement.style.setProperty(
    '--ck-color-list-button-hover-background',
    theme.palette.action.hover,
  );
  document.documentElement.style.setProperty(
    '--ck-color-list-button-on-background',
    theme.palette.action.selected,
  );
  document.documentElement.style.setProperty(
    '--ck-color-list-button-on-text',
    theme.palette.text.primary,
  );
  document.documentElement.style.setProperty(
    '--ck-color-panel-background',
    theme.palette.background.paper,
  );
  document.documentElement.style.setProperty(
    '--ck-color-panel-border',
    theme.palette.divider,
  );
  document.documentElement.style.setProperty(
    '--ck-color-toolbar-background',
    theme.palette.background.paper,
  );
  document.documentElement.style.setProperty(
    '--ck-color-toolbar-border',
    theme.palette.divider,
  );
  document.documentElement.style.setProperty(
    '--ck-color-tooltip-background',
    theme.palette.background.paper,
  );
  document.documentElement.style.setProperty(
    '--ck-color-tooltip-text',
    theme.palette.text.primary,
  );
  document.documentElement.style.setProperty(
    '--ck-color-image-caption-background',
    theme.palette.background.paper,
  );
  document.documentElement.style.setProperty(
    '--ck-color-image-caption-text',
    theme.palette.text.primary,
  );
  document.documentElement.style.setProperty(
    '--ck-color-widget-blurred-border',
    theme.palette.divider,
  );
  document.documentElement.style.setProperty(
    '--ck-color-widget-hover-border',
    theme.palette.action.hover,
  );
  document.documentElement.style.setProperty(
    '--ck-color-widget-editable-focus-background',
    theme.palette.action.hover,
  );
  document.documentElement.style.setProperty(
    '--ck-color-link-default',
    theme.palette.primary.main,
  );
  document.documentElement.style.setProperty(
    '--ck-color-base-border',
    theme.palette.divider,
  );
  document.documentElement.style.setProperty(
    '--ck-color-toolbar-border',
    theme.palette.divider,
  );
};
